### ISSUE TITLE
External link to project page on source platform

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#100]
On the project details page, there is an external link icon at the top. This icon when clicked should open a new tab that leads to the project page of the project on the source platform.

e.g https://staging.devouch.xyz/project/giveth/1 -> click external link button -> new tab to https://giveth.io/donate/the-giveth-community-of-makers

We should be able to handle this for all source platforms

There should be a small hover tooltip that explains to the user what this icon does.

https://www.figma.com/design/QBvhJZY3C93a8NKqcMnEHX/DeVouch?node-id=6980-9957&t=ylKIqQViHfIWf1QQ-1
![image](https://github.com/Giveth/DeVouch-FE/assets/67759413/422d5bbd-3aac-474c-9ca4-b0339f69cad1)

**Comment by maryjaf** [comment]
This issue has been resolved.
