### ISSUE TITLE
Duplicate projects showing for retro funding 4 source

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#104]
When filtering for rf4 projects there appears to be a few duplicates included in the response, why is this happening?

https://github.com/Giveth/DeVouch-FE/assets/67759413/9f122b39-4f28-45ae-8cd5-d0e2c36e3864

**Comment by MohammadPCh** [comment]
it's weird but they are different projects with different Ids.
<img width="1746" alt="Screenshot 2024-06-10 at 3 01 21 PM" src="https://github.com/Giveth/DeVouch-FE/assets/17097576/85d9753d-d06c-41e9-b6cf-c240d5f95cc5">

**Comment by divine-comedian** [comment]
Maybe we find a way to remove duplicates by project title ?
