### ISSUE TITLE
not showing project title in user attestations page

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#105]
in the public / private view of the user attestations page the section to show the project title is not showing any text for projects from the source `rpgf3`

why does this happen?

![Screenshot from 2024-06-06 09-34-31](https://github.com/Giveth/DeVouch-FE/assets/67759413/eeff7c57-e149-4986-ba2c-375ae0214cf3)

**Comment by MohammadPCh** [comment]
@divine-comedian  Since we don't import rpgf3 projects anymore they don't have details.
