### ISSUE TITLE
attester organization I am part of not showing to attest as

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#106]
I am part of the "Honorary Mexican" attester organization

While I am connect to the dapp with `0x826976d7C600d45FB8287CA1d7c76FC8eb732030`
The Honorary Mexican group shows as an option in the filter menu, but not as an option for me to vouch with...

here is the attestation that I received to make me part of the organization
https://sepolia.easscan.org/attestation/view/0xde3eec16282a71b74e14cbfbc0de7a0d06bbc3c45dff4cf043335e9f2c7687f8

and the corresponding migration file on the DB
https://github.com/Giveth/DeVouch-BE/blob/develop/db/migrations/1727705021366-AddHonorary%20Mexican.js

According to this I should be eligible to vouch using this attester org 

I'm also having the same with another group I added called "Degen"
https://sepolia.easscan.org/schema/view/0xa8122bdee6c8949308c097c2b28ab3d154bf4f27bf5a1e850a91884498b7de8c
https://github.com/Giveth/DeVouch-BE/blob/develop/db/migrations/1727705168214-AddDegen.js

**Comment by MohammadPCh** [comment]
@divine-comedian I checked it yesterday and noticed that the attestations occurred before the migration was applied, as there were no logs on the server for those UIDs. I have restarted the server, and it should be fine now.

**Comment by divine-comedian** [comment]
> @divine-comedian I checked it yesterday and noticed that the attestations occurred before the migration was applied, as there were no logs on the server for those UIDs. I have restarted the server, and it should be fine now.

OK, very strange, how is that possible though? The migration should have ran because the attester org shows up in the filters, so it should have shown up at the same time for being able to vouch with it on the FE..

**Comment by divine-comedian** [comment]
We need to figure out how to handle existing organizations - ideally we should be able to add a schema with attestations already distributed from issuing authority and it should start working right away

consider an organization like gitcoin passport - they have 


need to define start block in config

**Comment by divine-comedian** [comment]
if we want to look for attestations that have already happened, we need to drop the database and index again, that start block should be behind the first attestation that was made with elgibile attester organization

add a first block - we look at the earliest block among all tracked attester organization.

if the org has made at least 1 attestation previously, before migration was ran in BE then we need to drop

**Comment by aminlatifi** [comment]
> if we want to look for attestations that have already happened, we need to drop the database and index again, that start block should be behind the first attestation that was made with elgibile attester organization
> 
> add a first block - we look at the earliest block among all tracked attester organization.
> 
> if the org has made at least 1 attestation previously, before migration was ran in BE then we need to drop

@divine-comedian I changed the way a new organisation add PR is made, please read the readme and update it as you wish
