### ISSUE TITLE
space between header and the body [Except homepage]

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/DeVouch-FE#111]
On all pages, except the homepage!

---

<img width="1414" alt="Screenshot 2024-06-10 at 12 06 07 PM" src="https://github.com/Giveth/DeVouch-FE/assets/13708322/3068f338-4d5e-4d24-8163-42bc83efe90f">

The space between the heading and the body right now is **160px**.

It should be **90px.**

**Comment by MohammadPCh** [comment]
@mosaeedi the gap is 6rem equals to 96px.

**Comment by mosaeedi** [comment]
Can you please reduce that to 2rem?
