### ISSUE TITLE
Page Metadata 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#122]
We should handle showing the appropriate metadata for devouch 

All projects page -> title: "DeVouch | Decentralized Vouching for the Projects you Trust"
Project Details Page -> "DeVouch | {projectTitle} Details"
User Attestations (public) -> title: "DeVouch | {user address or ENS name) Attestations"
My Attestatsions -> title: "DeVouch | My Attestations"

description: "DeVouch is a system for members of reputable organizations in the Ethereum ecosystem to vouch for projects that are looking to raise funding."
image: 

![x-twitter](https://github.com/Giveth/DeVouch-FE/assets/67759413/0530ca7d-cea7-4270-a347-fad23bbc61c5)

We should be able to format this link to handle og and twitter property tags

**Comment by MohammadPCh** [comment]
@divine-comedian I added all of them, we need consider these:
1. It's time-consuming to add ens to the title because it's on the server side, and we need to wait for the request to resolve.
2. we need a description for the user page.

**Comment by divine-comedian** [comment]
> @divine-comedian I added all of them, we need consider these:
> 
> 1. It's time-consuming to add ens to the title because it's on the server side, and we need to wait for the request to resolve.
> 2. we need a description for the user page.

OK, let's leave out the ENS resolver in the metadata. 

user page (public) description: 

> View projects flagged or vouched by {address} using DeVouch.

**Comment by divine-comedian** [comment]
testing this out and found some issues @MohammadPCh 

![image](https://github.com/Giveth/DeVouch-FE/assets/67759413/35078203-2102-4964-a652-df8f90704369)


- [ ] the image is broken and does not render from the metadata on all pages
- [ ] my attestation page does not show correct description
- [ ] my attestations - incomplete title
- [ ] project details page - missing metadata description
