### ISSUE TITLE
When clickable, we need a pointer!

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/DeVouch-FE#126]
In this situation when this area is clickable, the cursor should turn into the pointer.

<img width="574" alt="Screenshot 2024-06-11 at 1 23 29 PM" src="https://github.com/Giveth/DeVouch-FE/assets/13708322/d62dc3b7-9699-46a1-a318-b207e4e6194d">

## How it should be?

<img width="989" alt="Screenshot 2024-06-11 at 1 26 40 PM" src="https://github.com/Giveth/DeVouch-FE/assets/13708322/8889d7b7-815d-4d8c-9d12-5fde1ef3b6dd">

**Comment by MohammadPCh** [comment]
So you mean if the card count exceeds 4, we need to display an additional card with a "+1" label, and ensure that the entire area is clickable.

**Comment by mosaeedi** [comment]
Nope!

right now, that area is clickable, the only thing we need to do is just turn the mouse [ ↗ ] cursor into a pointer [ 👆 ] on the clickable area!

<img width="29" alt="Screenshot 2024-06-11 at 3 27 36 PM" src="https://github.com/Giveth/DeVouch-FE/assets/13708322/4e4c120f-1af3-4462-a72c-ab12261b3d93">


I'm not talking about the card count exceeding 4....

**Comment by mosaeedi** [comment]
It's right!
Thanks.
