### ISSUE TITLE
Strange numbers when wallet is not connected

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/DeVouch-FE#140]
When user wallet is **[ not connected ]** and opens a project to view details, **Your attestation, All attestations and vouched** have the same count! which is not logical.

<img width="763" alt="Screenshot 2024-06-15 at 11 20 10 AM" src="https://github.com/Giveth/DeVouch-FE/assets/13708322/f136654b-4965-4638-b6cc-81d7a698e2df">

**Comment by maryjaf** [comment]
Thanks @mosaeedi
 It seems it has been changed 
when I tested the scenarios related to not connected user, "your attestations" was shown zero on STG 
could you please take a look @MohammadPCh

**Comment by maryjaf** [comment]
The number is shown 0 but there are attestations in list of my attestation @MohammadPCh 

![image](https://github.com/Giveth/DeVouch-FE/assets/111529185/e6c6d5ce-d5e3-417e-a2fe-908010cb57bf)

**Comment by MohammadPCh** [comment]
It seems the problem was fixed a long time ago.
