### ISSUE TITLE
Handle filter and attestation flow when user does not belong to any attester org

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#157]
We'll need to handle the front-end when a connected user does not belong to any attester org issues an attestation or wants to filter by these "No Affiliation" attestations. "No Affiliation" attester and attestations will be treated as a new attester org.

**This issue needs https://github.com/Giveth/DeVouch-BE/issues/107 to be deployed on staging in order to complete the work.**

## Attesting

When issuing an attestation from an address that does not belong to any attester org we should show a slight variation of the text on the modal that pop ups after user clicks VOUCH or FLAG

https://www.figma.com/design/QBvhJZY3C93a8NKqcMnEHX/DeVouch?node-id=6744-17595&t=mA5wwhnhAHGDyRzs-1
![Image](https://github.com/user-attachments/assets/318575d7-02df-406f-9d50-f5d6ede4b0e7)

## Filtering

we should show the "No Affiliation" filter on all regular views and handle filtering correctly on the following pages: 

- all projects page 
- project details page 
- my attestations page
- user attestations page

**Comment by Tosinolawale** [comment]
![Property 1=Not Eligible](https://github.com/user-attachments/assets/155a3d46-9810-415a-a146-60c012f66df5)
https://www.figma.com/design/QBvhJZY3C93a8NKqcMnEHX/DeVouch?node-id=6744-17595&t=mA5wwhnhAHGDyRzs-1
@divine-comedian

**Comment by Tosinolawale** [comment]
![Vouched list modal](https://github.com/user-attachments/assets/77352207-25f1-419e-8ada-3c332c83ba7a)
https://www.figma.com/design/QBvhJZY3C93a8NKqcMnEHX/DeVouch?node-id=7420-18869&t=mA5wwhnhAHGDyRzs-1
we should also show the No affiliation group on the project card

**Comment by Tosinolawale** [comment]
same for the project filters
![Property 1=Default](https://github.com/user-attachments/assets/19654f07-9fa5-4ff1-bd60-1e05736b7859)
https://www.figma.com/design/QBvhJZY3C93a8NKqcMnEHX/DeVouch?node-id=6732-9488&t=mA5wwhnhAHGDyRzs-1
@divine-comedian

**Comment by divine-comedian** [comment]
## first
is on this page when I'm vouching and I DO belong to some attester groups I should not see the option to choose No Affiliation



![Image](https://github.com/user-attachments/assets/67dd740b-dfb6-4f1c-82c2-ea5029318e01)

## second thing
on the my attestations page when I click Edit and try to change my vouch or flag I get an error on the console



https://github.com/user-attachments/assets/b4ccc7ca-f3ae-49a9-b3ed-f76df5aefda0

**Comment by LatifatAbdullahi** [comment]
@divine-comedian @mateodaza 

Show "No Affiliation" on Project card after Attesting - Pass
Filter "Flagged" or "Vouched" on Projects page - Pass
Filter "No Affiliation" and others (RTF5Project Page) - Pass
Filter "Flagged" or "Vouched"  (RTF5 Projects page - Pass

Filter "No Affiliation"  and others (Project Page) - Pass
Filter "No Affiliation"  and others(Home page) - Pass

Filter Attestation by "No Affiliation" and others in My Attestation - Pass
Filter Attestation by "Vouched" and others in My Attestation - Pass
Filter Attestation by "Flagged" and others in My Attestation - Pass

Filter Attestation by "No Affiliation" and others in Users Attestation - Pass
Filter Attestation by "Vouched" and others in Users Attestation - Pass
Filter Attestation by "Flagged" and others in Users Attestation - Pass

Edit Attestation(Vouch) in my Attestation - Pass
Edit Attestation (Flag) in my Attestation- Pass
Delete Attestation(Cancel)in  my Attestation- Pass
Delete Attestation(Confirm) in my Attestation - Pass

Filter Attestation by "No Affiliation" and others in Users Attestation - Pass
Filter Attestation by "Vouched" and others in Users Attestation - Pass
Filter Attestation by "Flagged" and others in Users Attestation - Pass
Edit Attestation(Vouch) in Users Attestation - Pass
Edit Attestation (Flag) in Users Attestation- Pass
Delete Attestation(Cancel) in Users Attestation- Pass
Delete Attestation(Confirm) in Users Attestation - Pass
