### ISSUE TITLE
Allow users to share their successful attestation on social media

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#169]
We should allow users to share their successful attestation (vouch ONLY) on social media networks! We should have some clickable icons available from the success modal 

https://www.figma.com/design/QBvhJZY3C93a8NKqcMnEHX/DeVouch?node-id=7079-29366&t=7mqpfnLSJyUT4ZrW-1
![image](https://github.com/user-attachments/assets/09940a25-97fa-46af-8550-8f9499a04b6b)
https://www.figma.com/design/QBvhJZY3C93a8NKqcMnEHX/DeVouch?node-id=8229-11040&t=7mqpfnLSJyUT4ZrW-1
![image](https://github.com/user-attachments/assets/0bc3218c-150d-4281-b45d-3e8cb3140e33)
### copy 
for share text it should be the following, based on which platform they are sharing on:

### twitter

I just vouched for this project on DeVouch! 
{projectLink} 

Use `@devouchxyz` to vouch for projects that you believe are legitimate and build networks of trust.

### farcaster
I just vouched for this project on DeVouch! 
{projectLink} 

Use DeVouch by `@giveth` to vouch for projects that you believe are legitimate and build networks of trust.

### facebook & linkedin

I just vouched for this project on DeVouch! 
{projectLink} 

Use DeVouch by `@giveth` to vouch for projects that you believe are legitimate and build networks of trust.

# AC

- [x] share button shows on successful vouch modal
- [x] share modal shows options to share message on farcaster, facebook, linkedin, twitter
- [ ] share button does not show on successful flag
- [ ] social share icons can be clicked and can successfully draft message to be posted on user's corresponding social feed
- [ ] share message properly tag devouch or giveth  accounts inside of messaging
- [x] project link is correct
- [x] share modal includes link to project page that can be copied to clipboard

**Comment by divine-comedian** [comment]
missing copy text to insert into the share modal that pops up

**Comment by Tosinolawale** [comment]
https://www.figma.com/design/QBvhJZY3C93a8NKqcMnEHX/DeVouch?node-id=7079-29366&t=7mqpfnLSJyUT4ZrW-1
![Property 1=Attestation Succesful](https://github.com/user-attachments/assets/5709ab48-8be0-49c2-b784-47d5797671b7)

https://www.figma.com/design/QBvhJZY3C93a8NKqcMnEHX/DeVouch?node-id=8229-11040&t=7mqpfnLSJyUT4ZrW-1
![Share Attestation](https://github.com/user-attachments/assets/8bea835e-fa23-4794-b3eb-232d3be0c37e)
@divine-comedian

**Comment by mateodaza** [comment]
Sadly we can't add more content to Facebook and LinkedIn besides the link @divine-comedian
