### ISSUE TITLE
Show date of project creation on project card and project details page

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#175]
We should show the date the project was created on both the project card and project details page. 

We should show the year and month of the date. 

![image](https://github.com/user-attachments/assets/af2fe57b-f802-4cf5-bfb8-edf51643017f)

## AC

- [x] on eligible projects - Giveth and Gitcoin sourced projects, date is shown on project card 
- [x] on eligible projects - Giveth and Gitcoin sourced projects, date is shown on project details page 
- [x] date is in correct format and preceded by "Created at" text ( day month year)
- [x] ineligible projects (from Retro Funding) do not show date element on project card or project details page

**Comment by Tosinolawale** [comment]
https://www.figma.com/design/QBvhJZY3C93a8NKqcMnEHX/DeVouch?node-id=6600-2877&t=7mqpfnLSJyUT4ZrW-1
![Project details](https://github.com/user-attachments/assets/3f5b4874-fd0b-485f-8d2e-8089b428682c)

https://www.figma.com/design/QBvhJZY3C93a8NKqcMnEHX/DeVouch?node-id=6284-2128&t=7mqpfnLSJyUT4ZrW-1
![State=Default](https://github.com/user-attachments/assets/faf265be-41bb-4ee2-92c0-f366ab34182f)
@divine-comedian

**Comment by divine-comedian** [comment]
Thanks! We'll need to resolve https://github.com/Giveth/DeVouch-BE/issues/116 in order to move this to FE development so we can get the project data from the BE endpoint
