### ISSUE TITLE
make it easier to find the my attestations page

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#176]
some user feedback has indicated that it is too hard to find the "My Attestations" link - we should find how to make it easier to find, either by placing it directly on a navbar element, fixing it at the top of the page or another method.

## AC

- [ ] new header element shows on all projects page 
- [ ] color state changes on hover
- [ ] when user is not connected to website the element is hidden
- [ ] clicking element directs user to my attestations page

**Comment by divine-comedian** [comment]
@Tosinolawale will resolve that today

**Comment by Tosinolawale** [comment]
![Connected](https://github.com/user-attachments/assets/a9685057-0abf-4a72-9716-9f1dad963f4e)
https://www.figma.com/design/QBvhJZY3C93a8NKqcMnEHX/DeVouch?node-id=8254-22351&t=hBpBwKj3u9VZhGyO-1
@divine-comedian
