### ISSUE TITLE
[project card] show flag/vouch count data for project

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#18]
On the project card on the all projects page we should be able to show the count of flags and vouches this project has received from attester organizations that we track.

backend endpoint -> https://backend.devouch.xyz/graphql

the count should have the following features:

- [x] show title of attester organization 
- [x] show count of unique attesters belonging to organization that have attested
- [x] the section for vouch and flag is sorted from highest to lowest of attestations received from each organization

 
![Project card](https://github.com/Giveth/DeVouch-FE/assets/67759413/5b777c5a-113d-444b-a478-f0c4ac71bb11)

### related BE issue
https://github.com/Giveth/DeVouch-BE/issues/12

**Comment by maryjaf** [comment]
> * If a project has been attested by more than 4 organizations - clicking the "+" button opens a modal to show the full list of counts from attester organizations

I couldn't test this AC @divine-comedian

**Comment by divine-comedian** [comment]
I'm in the process of trying to add more attester organizations to let us test this problem, had some tech issues on both the FE and BE

**Comment by MohammadPCh** [comment]
Guys, I  cut this from mvp scope 😄

**Comment by divine-comedian** [comment]
> Guys, I cut this from mvp scope 😄

OK, I made a new issue #97  to follow this up post MVP, we won't have more than 4 attester orgs at launch so its okay
