### ISSUE TITLE
Handle RF6 projects on all projects page

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#183]
Related to:
- https://github.com/Giveth/DeVouch-BE/issues/128
- https://github.com/Giveth/DeVouch-BE/issues/127

We'll need to handle the FE for incoming retro funding 6 projects. 

- filter for retro funding 6 projects 
- project card for RF6 projects 
- badge for Retro Funding 6 on Project card 

## AC

- [ ] project cards for retro funding 6 applications show up on all projects page
- [ ] title shows correctly
- [ ] banner image shows correctly
- [ ] description preview shows correctly
- [ ]  Retro Funding 6 Badge shows correctly (top right corner on top of banner image)
- [ ] can successfully vouch from project card
- [ ] can successfully FLAG from project card
- [ ] vouch & flag amounts shows correctly on project card

**Comment by divine-comedian** [comment]
@mateodaza can we confirm this is done and already on production? 

Did we do any QA on this?

**Comment by mateodaza** [comment]
@divine-comedian yes it's live
