### ISSUE TITLE
Handle Retro Funding 6 projects from project details page

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#184]
Related to:
- https://github.com/Giveth/DeVouch-BE/issues/128
- https://github.com/Giveth/DeVouch-BE/issues/127

We'll need to add support for Retro Funding 6 projects on the project details page  - e.g. https://devouch.xyz/project/rf/0xf839a585342327848d4541a6fcc315404e879537a60a1370f2cd45a94283a1ba

We will need to make sure attestation data tables work correctly - link to the source page (retrolist.app) and all project information is loaded correctly. 

- can display all data about project correctly: banner, description, title, source platform link, Source badge (Retro Funding 6) 
- table displays data correctly and with acceptable delays: vouched, flagged, my attestations, all attestations
- filtering works correctly for "Attested By" 
- vouching and flagging button work

## AC

- [ ] project details page for retro funding 6 applications can be navigated and opened successsfully
- [ ] title shows correctly
- [ ] banner image shows correctly
- [ ] descriptionshows correctly
- [ ]  Retro Funding 6 Badge shows correctly (top right corner on top of banner image)
- [ ] can successfully vouch from project details page
- [ ] can successfully FLAG from project details page
- [ ] vouch, flag, my attestations, and all attestations tables shows correctly on details page
- [ ] source platform link (arrow in top right corner of page) links correctly to project page on retrolist.app
- [ ] filter "Attested By" works correctly 
- [ ] share project button successfully copies project link

**Comment by divine-comedian** [comment]
@mateodaza - can we confirm this is totally done and on production? Did we do any QA on this?

**Comment by mateodaza** [comment]
yes ser @divine-comedian we're live
we were rushing that day so forgot to mention @LatifatAbdullahi

**Comment by LatifatAbdullahi** [comment]
Okay, I will test it and get back with report.

**Comment by LatifatAbdullahi** [comment]
@mateodaza @divine-comedian 

**Test Update**

- Project details page for retro funding 6 applications can be navigated and opened successsfully - **Pass**
- Title shows correctly - **Pass**
- Banner image shows correctly - **Pass**
- Description shows correctly - **Pass**
- Retro Funding 6 Badge shows correctly (top right corner on top of banner image) - **Pass**
- Can successfully vouch from project details page - **Pass**
- Can successfully FLAG from project details page - **Pass**
- Vouch shows correctly on details page - **Pass**
- Flag shows correctly on details page - **Pass**
- My attestations  shows correctly on details page - **Pass**
- All attestations tables shows correctly on details page - **Pass**
 - Filter "Attested By" works correctly - **Pass**
 - Share project button successfully copies project link - **Pass**
 
  - Source platform link (arrow in top right corner of page) links correctly to project page on retrolist.app - **Failed**

Although  Users are redirected to the Retrolist page, it does not show the Projects page on Retrolist, rather this **" Wait a moment - Retrolist is assembling everything"**


![image](https://github.com/user-attachments/assets/c076a240-5778-41c2-af67-dac89bd0906b)

**Comment by divine-comedian** [comment]
thanks @LatifatAbdullahi - it looks like it only affects certain projects and it is a bug related to retrolist - I forwarded this report to their developer
