### ISSUE TITLE
sorting project cards

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#21]
We should be able to sort the list of all projects in various ways. 

by default we sort the projects based on the highest count of attestations on a given project - totaled across all tracked attester organizations 

other sorting options include:

- highest vouch count - projects that have the highest total count of vouches across all tracked attester orgs
- lowest vouch count - projects that have the lowest total count of vouches across all tracked attester orgs
- highest flags - projects that have the highest total count of flags across all tracked attester orgs
- lowest flags - projects that have the lowest total count of flags across all tracked attester orgs

![Sort by modal](https://github.com/Giveth/DeVouch-FE/assets/67759413/51fc7b75-f86b-462c-b107-fe10e18ca371)

### Realted BE issues
https://github.com/Giveth/DeVouch-BE/issues/48
https://github.com/Giveth/DeVouch-BE/issues/30

## AC

- [x] default sorting by highest count of attestations across all att. orgs.
- [x] can sort by highest vouch count
- [x] can sort by lowest vouch count
- [x] can sort by highest flags
- [x] can sort by lowest flags

**Comment by maryjaf** [comment]
The sorting options works correctly but the naming of sorting options are different from picture in description, which is the final design?

![image](https://github.com/Giveth/DeVouch-FE/assets/111529185/d38cd8bd-8d2f-4bb6-9b87-284bb8d5d085)

**Comment by divine-comedian** [comment]
@maryjaf @MohammadPCh - the naming should follow what I've posted above in this issue.

**Comment by maryjaf** [comment]
> @maryjaf @MohammadPCh - the naming should follow what I've posted above in this issue.

Kindly reminder @MohammadPCh

**Comment by divine-comedian** [comment]
Just pushed a fix to develop for this text - its now on staging

![image](https://github.com/Giveth/DeVouch-FE/assets/67759413/91d09c15-46dd-40b3-a555-55afb2a680bc)
