### ISSUE TITLE
connect with web wallet

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#24]
we should handle the connect with web wallet component using web3modal - user should be able to connect to the app with their web wallet or handle connection via wallet connect on mobile.

there are two states, signed in and not signed in.

### not signed in 
![image](https://github.com/Giveth/DeVouch-FE/assets/67759413/ba661d55-438f-44e0-8182-23332568afdc)

## signed in
![Wallet dropdown](https://github.com/Giveth/DeVouch-FE/assets/67759413/5b35d6c4-dd51-4a11-a892-6f708ce057bb)

this also includes a link to the documentation for DeVouch (link pending)

**Comment by maryjaf** [comment]
It has been passed.
