### ISSUE TITLE
responsive views of all projects page

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#25]
We should handle the responsive design views for the all projects page. 

### Figma
https://www.figma.com/design/QBvhJZY3C93a8NKqcMnEHX/DeVouch?node-id=6980-25398&t=6wskr8Jhot06NEIS-1
![image](https://github.com/Giveth/DeVouch-FE/assets/67759413/1f0b15b6-2737-4c25-a76f-1dac17c2e217)

**Comment by maryjaf** [comment]
Device:iPhone 12
Browser: chrome and safari

project cord isn’t shown correctly
Remove icon isn’t shown in user page

https://github.com/Giveth/DeVouch-FE/assets/111529185/ff0c0965-293c-4333-9e6e-b6e3186280f9


https://github.com/Giveth/DeVouch-FE/assets/111529185/cfac9c1b-9b4f-4630-9586-faa069c6a806
@MohammadPCh

**Comment by maryjaf** [comment]
Problem in showing filter in project page 

https://github.com/Giveth/DeVouch-FE/assets/111529185/7ea33ea2-f9e8-4380-b151-030f5d79ca67

**Comment by divine-comedian** [comment]
@MohammadPCh  I saw your PR is merged - is this ready to be tested again?

**Comment by maryjaf** [comment]
> Device:iPhone 12 Browser: chrome and safari
> 
> * [x]  - project cord isn’t shown correctly


This item has been fixed, the other two items remain

**Comment by divine-comedian** [comment]
- [ ] the comments icon shows over top of the filter drop down menu


![image](https://github.com/Giveth/DeVouch-FE/assets/67759413/fc58f9ae-fd7a-4077-b7ee-314f31388041)
