### ISSUE TITLE
[project card] hover/loading state

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#28]
We should handle any hover and loading states of the project page. as well as any conditional states based on lack of vouch/flag data for a given project. 

###  if the user is hovering the project card, we should handle showing the colour of the attestations count "badges"
![Project card-hover](https://github.com/Giveth/DeVouch-FE/assets/67759413/c77a2991-82db-4d9a-be7b-e01feae3b36f)

### while the project info is loading 
![Project card-loading](https://github.com/Giveth/DeVouch-FE/assets/67759413/a5a4fe56-956f-4bfa-9f2f-09cdfe05b2b3)

### if there are no vouches/flags for given project
![image](https://github.com/Giveth/DeVouch-FE/assets/67759413/1e3bbd2c-9035-4b09-8f9e-97df84047f5a)

## Figma
https://www.figma.com/design/QBvhJZY3C93a8NKqcMnEHX/DeVouch?node-id=6980-11933&t=6wskr8Jhot06NEIS-1

## AC

- [x] when project info is loading the loading state is shown
- [ ] when project is hovered it shows the correct state
- [x] when a project hasn't received any vouches we show correct empty state for "vouched by"
- [x] when project hasn't received flags we show empty state for "flagged by"

**Comment by divine-comedian** [comment]
@MohammadPCh - to confirm, due to the limitations of tailwind CSS we will ignore the feature of adding unique colours to the attester organizations when hovered, correct?

**Comment by MohammadPCh** [comment]
@divine-comedian Yes, we have 2 solutions:
1. have a list of colors that we going to use for the organizations for instance you can pass me a list of 100 colors.
2. handle them by js.

I prefer the first solution since it's easier 😄

**Comment by divine-comedian** [comment]
> @divine-comedian Yes, we have 2 solutions:
> 
> 1. have a list of colors that we going to use for the organizations for instance you can pass me a list of 100 colors.
> 2. handle them by js.
> 
> I prefer the first solution since it's easier 😄

let's not handle any colours for now but the 2nd option is better since it gives more flexibility for the external org - I will make a separate issue we can follow after MVP
