### ISSUE TITLE
Allow user to attest to multiple projects at once

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#30]
We should take this one up once we finish the MVP - we should research if it is possible to vouch or flag for multiple projects in one transaction. 

I know there is such a thing as batch attestation but I had trouble finding documentation for it. Maybe @kristoferlund knows..

**Comment by kristoferlund** [comment]
@divine-comedian yup, there is a `multiAttest` function in the EAS SDK.

**Comment by kristoferlund** [comment]
@divine-comedian basically, it is as easy as creating one attestation. You provide an array of data instead of just on object.
