### ISSUE TITLE
show project information on project details

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#32]
we should show the project's relevant information on the project details page, this includes: 

- [ ] project title
- [ ] full description
- [ ] banner image
- [ ] project source
- [ ] link to project page on source platform
- [ ] source platform (giveth, gitcoin, retro-funding)

https://www.figma.com/design/QBvhJZY3C93a8NKqcMnEHX/DeVouch?node-id=6980-9957&t=6wskr8Jhot06NEIS-1
![image](https://github.com/Giveth/DeVouch-FE/assets/67759413/a5775869-99d6-4296-afa7-6d22e44d07b9)

## related BE issue 
https://github.com/Giveth/DeVouch-BE/issues/14

**Comment by divine-comedian** [comment]
@mateodaza  - let us know if there is a URL we can test this at

**Comment by maryjaf** [comment]
> * [ ]  link to project page on source platform
> *

The link of project page on source platform doesn't work correctly
I also left a comment on this issue https://github.com/Giveth/DeVouch-BE/issues/4#issuecomment-2149321720
