### ISSUE TITLE
attest to project (vouch/flag) from project details page

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#33]
The user should be able to start the vouch / flag attestation flow from the project details page. These flows are captured here - #26 #27 

![image](https://github.com/Giveth/DeVouch-FE/assets/67759413/98e8cc64-c82f-41e6-b13e-abe6d0620f01)

**Comment by mateodaza** [comment]
@MohammadPCh would you like to take this on, and I'll grab "My Attestations" page?

**Comment by maryjaf** [comment]
I've completed test of vouch/flag  flows and it works correctly 
the vouch/flag is shown in project detail and user detail
