### ISSUE TITLE
"filter" tabs on attestation data on project details page

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#34]
below the project information we should have a table showing the attestation data for the given project. this table should have the following columns: 

- attester address / date of attestation
- attester organization attested with
- comments (if applicable) on attestation
- if vouch/flag

apart from this there are 4 tabs that filter the attestation data

- attestations made by connected user
- all attestations (no filter)
- only vouches 
- only flags

https://www.figma.com/design/QBvhJZY3C93a8NKqcMnEHX/DeVouch?node-id=6980-9957&t=6wskr8Jhot06NEIS-1
![image](https://github.com/Giveth/DeVouch-FE/assets/67759413/e77c1a21-0c2e-4e7f-901b-5ee9a50181b9)

## related BE issues
https://github.com/Giveth/DeVouch-BE/issues/16
https://github.com/Giveth/DeVouch-BE/issues/20

## AC
the attestation data table contains the following information for each entry:

- [ ] date of attestation
- [ ] attester address or ENS name #53 
- [ ] attester organization
- [ ] comments icon
- [ ] comments content on hover
- [ ] if vouch or flag

the attestation table has three tabs above it which:

- [ ] attestations from connected user for given project
- [ ] only vouches made to this project (from all attestations)
- [ ] only flags made to this project (from all attestations)
- [ ] all attestations data (no filter)
- [ ] tab filters also apply other filters from #37 correctly to look for only attestations from certain attester organizations

**Comment by divine-comedian** [comment]
@mateodaza - saw this moved to UAT - do we have a link to test it?

**Comment by maryjaf** [comment]
> [ ] date of attestation

- [ ] 1-"date of attestation" isn't shown in this list 

- [ ] 2-Is there no limitation for number of character of comments ? take a look on below screen record 
@divine-comedian @mateodaza 
https://de-vouch-fe-git-develop-givethio.vercel.app/project/gitcoin/0x046243579fe09f747cd9194e0cf0521c202761b096ebcbf11d22e55c3ae4c9a8

https://github.com/Giveth/DeVouch-FE/assets/111529185/28ed9bff-a984-441a-a4fc-55a866c29f3a

**Comment by maryjaf** [comment]
- [ ] 3- I attest a project with different organization, but the counter on "all Attestation" and "flag" tab counts these as one vouch/flag

for example in below screen record
- I flag this project with "trace" and "giveth" organization but the flag's counter shows 1 

https://github.com/Giveth/DeVouch-FE/assets/111529185/cefaf0ae-0b24-4ad4-808a-53dbc5d385a7

**Comment by maryjaf** [comment]
> * [x]  3- I attest a project with different organization, but the counter on **"all Attestations"** and **"flag"** tabs counts these as one vouch/flag
> 
> for example in below screen record
> 
> * I flag this project with "trace" and "giveth" organization but the flag's counter shows 1
> 
>  Screen.Recording.2024-06-05.at.3.19.41.PM.mov

It seems I tested on a old link https://de-vouch-fe-git-develop-givethio.vercel.app/
and on the new link this problem has been resolved 

only # 1 and # 2 should be checked

**Comment by divine-comedian** [comment]
@maryjaf nice catch! the comments added from vouching/flagging and editing should be limited to 256 characters.

The date of attestation can be found below the address of the attester in the same column

**Comment by maryjaf** [comment]
The limitation has been added.
