### ISSUE TITLE
pagination of attestation data on project details

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#35]
we should show a limited amount of attestation data on the project details page. up to 10 rows of information

the user should be able to use pagination to see different rows of attestation in increments of 10 rows per view. Any relevant tabs or filtering should be taken into consideration.

![image](https://github.com/Giveth/DeVouch-FE/assets/67759413/2ab75d2e-c725-4e04-941d-0b8710fbdbbd)

## AC

- [ ] attestation data can be cycled by 10 entries at a time on the attestation data table 
- [ ] attestation data is shown correctly without duplicate entries while searching across pagination
- [ ] sort features for project title and date of attestations work correctly across paginated table
- [ ] "tab filters" pagination works correctly 
- [ ] attester organization filter works correctly 
- [ ] pagination handles combinations of filter and sorting correctly

**Comment by divine-comedian** [comment]
@mateodaza - is there a link to test this?

**Comment by mateodaza** [comment]
I think the PR is moving the issues automatically- once I have a link I'll share it, we need to solve a build issue that's occurring on main branch
