### ISSUE TITLE
share project button

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#36]
we should have a button that allows projects to easily click a button which copies the project details URL to their clipboard. 

![image](https://github.com/Giveth/DeVouch-FE/assets/67759413/c8b343eb-a93b-4263-b202-285582f128ee)

**Comment by divine-comedian** [comment]
@MohammadPCh - Did you make any progress on this? Are you missing any states from the design with this button?

**Comment by divine-comedian** [comment]
Need state for when share button is clicked from @mosaeedi

**Comment by mosaeedi** [comment]
Take a look here -> [Figma link](https://www.figma.com/design/QBvhJZY3C93a8NKqcMnEHX/DeVouch?node-id=8024-13920&m=dev)

### Default state:

<img width="238" alt="Screenshot 2024-06-19 at 5 12 32 PM" src="https://github.com/Giveth/DeVouch-FE/assets/13708322/80289e7b-7279-41cf-95ff-9b0e14e03a8a">


Clicked state: (For 4 seconds)

<img width="186" alt="Screenshot 2024-06-19 at 5 13 31 PM" src="https://github.com/Giveth/DeVouch-FE/assets/13708322/033cae49-5eb9-46bf-a6a4-8301974718d1">

**Comment by divine-comedian** [comment]
tested an appears to work as expected! closing this one.
