### ISSUE TITLE
filter menu on project details

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#37]
on the attestation data table on the project details page we should be able to apply a filter from the filter menu, from this filter menu the user will be able to filter by attestatsion made from a specific (or several) attester organizations.

https://www.figma.com/design/QBvhJZY3C93a8NKqcMnEHX/DeVouch?node-id=7160-16199&t=6wskr8Jhot06NEIS-1
![Project detail Filter modal](https://github.com/Giveth/DeVouch-FE/assets/67759413/61e9392c-5522-4759-b77e-6692c4b861ff)

## related BE issue 
https://github.com/Giveth/DeVouch-BE/issues/19

## AC

- [x] can select one or more attester organizations to filter by
- [x] filtering attester orgs shows the correct data
- [x] no attestations from other attester organizations appear in the attestation data table

filtering by attester organization works in the following scenarios:

- [x] while on the "your attestations tab"
- [x] while on only flags tab
- [x] while on only vouches tab

**Comment by divine-comedian** [comment]
@mateodaza  - saw this moved to UAT, do we have a link for testing?

**Comment by maryjaf** [comment]
- [ ] when I set a filter the tab's counter isn't shown based on setting filter for "All attestations", "vouched" and "flagged" tabbs

for example 
-I flagged the project,  1 flag on trace and the other on giveth
-the counter on "flagged" and "my attestation" is 2 
-filter is set based on "trace"
-the counter of "my attestation" is changed to 1 correctly 
-but the counter of  "flagged" remains 2 (this problem also  exists for "All attestations" and"vouched"  tab)

Is this accepted result or should be changed? @divine-comedian @mateodaza 

https://github.com/Giveth/DeVouch-FE/assets/111529185/696feee2-0ab5-4351-b93c-69cc7907e9f4

**Comment by divine-comedian** [comment]
you're right! with the filter applied the tabs should show the correct count. This is a minor issue, we can fast follow after launch on this small bug @MohammadPCh

**Comment by divine-comedian** [comment]
@MohammadPCh  - I think I heard you talk about this on one of your check-ins, did you end up fixing this? 



> * [ ]  when I set a filter the tab's counter isn't shown based on setting filter for "All attestations", "vouched" and "flagged" tabbs
> 
> for example -I flagged the project, 1 flag on trace and the other on giveth -the counter on "flagged" and "my attestation" is 2 -filter is set based on "trace" -the counter of "my attestation" is changed to 1 correctly -but the counter of "flagged" remains 2 (this problem also exists for "All attestations" and"vouched" tab)
> 
> Is this accepted result or should be changed? @divine-comedian @mateodaza
> 
>  Screen.Recording.2024-06-05.at.3.30.13.PM.mov

**Comment by MohammadPCh** [comment]
It seems that the problem is fixed. @maryjaf can you check it again? Thanks

**Comment by maryjaf** [comment]
> It seems that the problem is fixed. @maryjaf can you check it again? Thanks

It has been fixed.
