### ISSUE TITLE
user attestations page (private/public view)

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#42]
the user attestations page contains all info related to the attestations a user has made, it has two views 

- private view (accessible from navbar drop down menu)
- public view (accessible from clicking address on row entry on project details table)

### private view
the private view has the following features

- connect wallet
- header
- filter menu
- pagination
- footer
- attestation data table, which includes columns for:
  - project title 
  - date of attestation
  - comments 
  - if vouch/flag
  - edit button
  - delete button
- sorting options on columns
- filter tabs above table

![Attester Profile](https://github.com/Giveth/DeVouch-FE/assets/67759413/25006e0a-05a3-473a-8acc-6b15c3306128)

## public view 

- connect wallet
- header
- filter menu
- pagination
- footer
- attestation data table, which includes columns for:
  - project title 
  - date of attestation
  - comments 
  - if vouch/flag
- sorting options on columns
- filter tabs above table
![Attester Profile (Public)](https://github.com/Giveth/DeVouch-FE/assets/67759413/f275b34b-62aa-43ec-84ac-b7bee972762c)

**Comment by maryjaf** [comment]
- [ ] 1- By switching between tabs in user page for a sec the counters are shown 0 

https://github.com/Giveth/DeVouch-FE/assets/111529185/2933c023-6b7c-4f0f-bbc4-c0603368b517

**Comment by divine-comedian** [comment]
NIce catch! There should be two columns that can handle sorting 

Projects - sort alphabetically ASC/DESC 
Date Attested - sort by newest/oldest

Each will need the sorting icon to the left of the column title as per the Figma

**Comment by MohammadPCh** [comment]
@maryjaf it's ready to test. thanks

**Comment by maryjaf** [comment]
I moved it to done.
