### ISSUE TITLE
handle when user is not connected to website

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#43]
when user is not connected with their wallet and they want to create an attestation, when they click the button it should trigger the web3modal pop-up for the user to log-in.

ALSO when the user is connected to the wrong network we should not let them attest on the wrong network! if they are not on the right network and click to vouch/flag/edit we should show them the switch network modal on their web wallet to connect to the correct network

## AC
when user is not logged in/connected with web wallet
- [x] clicking vouch button from project card opens web3 modal
- [x] clicking vouch button from project details page opens web3 modal
- [x] clicking flag button from project card opens web3 modal
- [x] clicking flag button from project details page opens web3 modal

**Comment by maryjaf** [comment]
> * clicking vouch button from project details page opens web3 modal
> * clicking flag button from project details page opens web3 modal

by clicking  vouch/flag button from project details page,  web3 modal isn't shown @MohammadPCh 

https://github.com/Giveth/DeVouch-FE/assets/111529185/4927e2e0-a6c8-470b-9314-b107be2aa0a5

**Comment by MohammadPCh** [comment]
@divine-comedian @maryjaf please recheck it, because I wrote a function that forces the user to switch to the target chain.

**Comment by maryjaf** [comment]
Yeah I saw this change in my tests, switch to sepolia is shown

**Comment by maryjaf** [comment]
> ALSO when the user is connected to the wrong network we should not let them attest on the wrong network! if they are not on the right network and click to vouch/flag/edit we should show them the switch network modal on their web wallet to connect to the correct network

in this case bay tapping on confirm button in flag/vouch modal the "switch network" is shown .

https://github.com/Giveth/DeVouch-FE/assets/111529185/b82acfda-d5db-4b57-b812-a99624e2dbff
