### ISSUE TITLE
attestation table of user attestations

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#44]
The attestation table on the private and public view of user attestations should have the following features: 

- [x] column for project title
- [x] column for date attestation
- [x] column for attester organization 
- [x] column for comment
- [x] column for signal (if vouch or flag)
- [x] additionally on the PRIVATE view there should one additional column for an actions - edit #45  and delete #46  

there should also be tabs that allow for some filtering of attestation data, including

- [x] all attestations (no filter)
- [x] vouched (only vouch attestations made by user)
- [x] flagged (only flag attestations made by user)

there should also be the ability to sort by certain column values, including:

- [x] sort by project title alphabetically ASC/DESC
- [x] sort by date of attestation ASC/DESC

by default the table should be sorted by the most recent attestations the user has made.

![Attestations](https://github.com/Giveth/DeVouch-FE/assets/67759413/f0744cd3-ca7c-4b20-9449-8ffed262dea4)

## related BE issues

https://github.com/Giveth/DeVouch-BE/issues/26
https://github.com/Giveth/DeVouch-BE/issues/23
https://github.com/Giveth/DeVouch-BE/issues/35
https://github.com/Giveth/DeVouch-BE/issues/28

**Comment by maryjaf** [comment]
I can see my attestation for a project only on project detail page -> "my attestation" tab, Is there a separate link for user page? @mateodaza

**Comment by maryjaf** [comment]
> [x] column for project title

I see I should test on https://staging.devouch.xyz/

**Comment by maryjaf** [comment]
> I can see my attestation for a project only on project detail page -> "my attestation" tab, Is there a separate link for user page? @mateodaza https://de-vouch-fe-git-develop-givethio.vercel.app/project/giveth/2880

I see I should test on https://staging.devouch.xyz/

**Comment by maryjaf** [comment]
> [x] column for project title

It shouldn't be clickable ? @divine-comedian

**Comment by divine-comedian** [comment]
> > [x] column for project title
> 
> The project title shouldn't be clickable ? @divine-comedian

It should be clickable! I made an issue here to cover this and other clickable sections of tables  #67

**Comment by maryjaf** [comment]
It has been fixed.
