### ISSUE TITLE
delete attestation flow

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#46]
a user should be able to "delete" their attestation, accessible from the private view of their attestations page or also from the "your attestations" tab on the project details view. 

deleting an attestation is the action of revoking the attestation on-chain using EAS. This should remove their attestation from the UI for the given project, as the given attester organization.

https://www.figma.com/design/QBvhJZY3C93a8NKqcMnEHX/DeVouch?node-id=7160-15269&t=YfP5lBRZXqLlXR7X-1
![Revoke](https://github.com/Giveth/DeVouch-FE/assets/67759413/c9766c36-e451-43b8-afb5-d31da7ae918b)

## AC

- [ ] user can click "trash can" button from either your attestations in project page or my attestation page
- [x] sees modal to delete attestation confirmation
- [x] generate on-chain tx to revoke attestation, is successful
- [x] see success modal
- [x] attestation is successfully removed from user attestations page 
- [x] attestation is successfully removed from project attestations page 
- [x] attestation is successfully removed from count of project attestations

**Comment by maryjaf** [comment]
> [ ] user can click "trash can" button from either your attestations in project page or my attestation page

- [ ] 1- There is no trash icon in project page ->my attestation

**Comment by maryjaf** [comment]
https://github.com/Giveth/DeVouch-FE/assets/111529185/44b2eec4-bf9c-4954-8ee8-f7d54e240cda

**Comment by divine-comedian** [comment]
@maryjaf please retest and let us know if this issue is approved.

**Comment by divine-comedian** [comment]
@MohammadPCh please review these bugs

**Comment by MohammadPCh** [comment]
@maryjaf @divine-comedian I couldn't reproduce it. let's check it together.

**Comment by maryjaf** [comment]
> @maryjaf @divine-comedian I couldn't reproduce it. let's check it together.

After  the last change the item 3 has been resolved but new bug that I’ve shared in the call appears 

I’ll check again and if there is no issue for that , I’ll create new bug issue

**Comment by maryjaf** [comment]
> * [ ]  1- There is no trash icon in project page ->my attestation

Thanks @MohammadPCh Item 2 and 3 have been resolved

Item 1 hasn't been added yet , Is this blocker for release or not? @divine-comedian

**Comment by divine-comedian** [comment]
@maryjaf - No it isn't I will make a new issue to follow it up in post MVP

On the project details page under the tab "Your Attestations the logged in user should have both the edit and delete attestation buttons.
