### ISSUE TITLE
filter menu on user attestations page

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#47]
on the private and public view on the user attestations page, we should be able to filter from the drop down menu by two things

- attester organization - filters for attestation user made only with given attester org
- source platform of project - filters for attestations made to projects only from given source platform (giveth, gitcoin, retro-funding)

https://www.figma.com/design/QBvhJZY3C93a8NKqcMnEHX/DeVouch?node-id=7160-16328&t=YfP5lBRZXqLlXR7X-1
![Filter Modal](https://github.com/Giveth/DeVouch-FE/assets/67759413/67fe3fd4-864c-4789-b9fc-a107ca0f19dc)

## related BE issues
https://github.com/Giveth/DeVouch-BE/issues/25
https://github.com/Giveth/DeVouch-BE/issues/24

**Comment by maryjaf** [comment]
- [ ] only "Source platform" filter exists in user page, "attest by" doesn't exist in user page

![image](https://github.com/Giveth/DeVouch-FE/assets/111529185/82743aff-566d-446c-be92-d1c136e641cf)

**Comment by divine-comedian** [comment]
@MohammadPCh FYI we also don't see this option on the project details page

**Comment by maryjaf** [comment]
> @MohammadPCh FYI we also don't see this option on the project details page

I see this filter in main page 
![IMG_2456](https://github.com/Giveth/DeVouch-FE/assets/111529185/5407343e-3531-4588-82e3-d485f10c4ee1)
So there is no need to show these filters in project and user page ?

**Comment by divine-comedian** [comment]
@maryjaf the filter options will be different depending on each page - there is a separate issue for each

**Comment by divine-comedian** [comment]
Still we should add a source platform filter to the user attestation page

**Comment by maryjaf** [comment]
It has been fixed
