### ISSUE TITLE
pagination of attestation table

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#48]
We should be able to handle pagination of attestation info on the table on the private and public view of the user attestations page. each page should handle 10 entries of attestation data.

![image](https://github.com/Giveth/DeVouch-FE/assets/67759413/5149c8c0-57c0-448c-8b0a-3023564e2f42)

**Comment by maryjaf** [comment]
I only have one address for vouching and I couldn't  test the pagination.

**Comment by divine-comedian** [comment]
> I only have one address for vouching and I couldn't test the pagination.

@maryjaf - you should be able to test this issue by using a single address to attest to many projects, since this is for the public/private view of the user attestations table 

You'll need to attest to > 20 different projects to test this one out properly

**Comment by maryjaf** [comment]
> > I only have one address for vouching and I couldn't test the pagination.
> 
> @maryjaf - you should be able to test this issue by using a single address to attest to many projects, since this is for the public/private view of the user attestations table
> 
> You'll need to attest to > 20 different projects to test this one out properly

Yeah , I thought it is related to pagination of project page table

**Comment by divine-comedian** [comment]
@maryjaf - Did you have a chance to create the sample data and test the pagination on the user attestations table?

**Comment by maryjaf** [comment]
> @maryjaf - Did you have a chance to create the sample data and test the pagination on the user attestations table?

Yeah, I've tested pagination in user's attestation page and it works correctly
