### ISSUE TITLE
resolve ENS names from addresses

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#53]
On the attestations table we should resolve the ENS names of addresses that have vouched or flagged the given project. 

![image](https://github.com/Giveth/DeVouch-FE/assets/67759413/5a3d41d5-e26e-4285-bdce-ed3aab1751c2)

## AC
on the project details page:

- [ ] addresses in project attestations table correctly resolve their ENS names

**Comment by divine-comedian** [comment]
@mateodaza - do we have a link to test this?

**Comment by MohammadPCh** [comment]
@divine-comedian to test: https://staging.devouch.xyz/

**Comment by divine-comedian** [comment]
@mateodaza sorry one more place we should show ENS names - on the user attestations page 

on the header we show the address - this should be the ENS name as well 

![image](https://github.com/Giveth/DeVouch-FE/assets/67759413/ba3db5fa-5927-4cf0-b2df-9768d7195ac8)

**Comment by maryjaf** [comment]
- [ ] The ENS name isn't shown in tables

**Comment by divine-comedian** [comment]
This isn't a release blocker so let's pick it up after MVP

**Comment by maryjaf** [comment]
It seems it hasn't been fixed @MohammadPCh 
<img width="1749" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWRZQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fba382ae2f2d333b6f43c9ff4d342d3fd267c900/image.png" alt="image.png" />
