### ISSUE TITLE
Fix project description lengths

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#65]
## Project cards
On the project cards the description should be limited to 60 characters.

Some projects also come with lots of raw markdown formatting, we should find a way to remove markdown syntax from the short project description (but maybe we can use it for the long description.

![image](https://github.com/Giveth/DeVouch-FE/assets/67759413/a9c25ac7-1a10-42bc-add2-491eae530d89)

----
## project details page

the description on the project details page should not be shortened - it appears Giveth projects have their descriptions shortened on both the details page and project card... 

also for projects that come with formatting/markdown syntax we should find a way to parse and show markdown formatted text in the long project description on the project details page

**Comment by MohammadPCh** [comment]
I've fixed the length, but to show the styled version, we need to convert it to the html on BE, I'll do it after the MVP.

**Comment by divine-comedian** [comment]
> I've fixed the length, but to show the styled version, we need to convert it to the html on BE, I'll do it after the MVP.

OK I've follow this up in https://github.com/Giveth/DeVouch-BE/issues/69

**Comment by maryjaf** [comment]
- [ ] I've checked the count of character for some project, please take a look on below pic number of character of giveth project  https://staging.devouch.xyz/project/giveth/1443 , it is more than 60 characters

![image](https://github.com/Giveth/DeVouch-FE/assets/111529185/45f7de1f-43e0-4edb-b0d9-1707e59d4c3b)

- [ ] it seems also in  project detail page this limitation exists
![image](https://github.com/Giveth/DeVouch-FE/assets/111529185/4bb9112d-9e4b-499a-8e2f-6b5f08681cda)

**Comment by divine-comedian** [comment]
@aminlatifi  mentiond that in the BE we are getting the truncated response from Giveth? The 'project description summary'. How can we fix this?

**Comment by MohammadPCh** [comment]
@divine-comedian @maryjaf For the description, we did the following:

1. Only show the first 300 characters of each description on the project card.
2. No limits for the description on the project details view.
3. Convert the markdown files to HTML to display styled descriptions.

@divine-comedian Regarding the length, do we need to limit it to 60 characters or 300 chars is eanough? We can easily make that change if needed.

**Comment by MohammadPCh** [comment]
The Gitcoin projects are in Markdown format, so limiting them to a specific number of characters is not easy. My suggestion is to show plain text for Gitcoin projects on the project card and display the styled version on the project details page.

**Comment by MohammadPCh** [comment]
@maryjaf Yeah, it's because the new PR is not merged yet on BE, after it you will see the latest results.

**Comment by aminlatifi** [comment]
https://github.com/Giveth/DeVouch-BE/issues/76#issuecomment-2158137173

**Comment by aminlatifi** [comment]
> @maryjaf Yeah, it's because the new PR is not merged yet on BE, after it you will see the latest results.

@MohammadPCh the API is ready

**Comment by maryjaf** [comment]
> But as you can see in above pic, this limitation also exists for "Giveth matching pool" project, only 300 characters are shown in project detail

Thanks @MohammadPCh 
It has been fixed.
