### ISSUE TITLE
projects shows as no data available!

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#66]
on the list of projects a card is showing with no data available! We should not show this card 

Could it be that it is fetching attestations for a projectId that doesn't exist? Since anyone can issue an attestation with any data maybe it's being indexed and fed to the FE

At any rate when we can't get any data for the project we should skip showing it on the FE.

![Screenshot from 2024-06-04 09-31-40](https://github.com/Giveth/DeVouch-FE/assets/67759413/48dd051c-9dec-4625-9d62-11803d383d72)

**Comment by MohammadPCh** [comment]
@divine-comedian Thanks, can you attach the screenshot? if we want to remove projects with no title, it's better to remove them from BE.

**Comment by divine-comedian** [comment]
> @divine-comedian Thanks, can you attach the screenshot? if we want to remove projects with no title, it's better to remove them from BE.

Just added the screenshot into the issue! Sorry I thought I did that. Can you please coordinate with @aminlatifi to figure out how we can solve this?

**Comment by aminlatifi** [comment]
@divine-comedian you are right. That project would be giveth-123, I attested with a random projectId,  and now is shown there. One way around this is changing the queries to only list projects with filled title or description fields! 
One more clear way is to define a flag in project entity, named `imported` and make it true when the entity is filled with real project data.

**Comment by aminlatifi** [comment]
> @divine-comedian you are right. That project would be giveth-123, I attested with a random projectId, and now is shown there. One way around this is changing the queries to only list projects with filled title or description fields! One more clear way is to define a flag in project entity, named `imported` and make it true when the entity is filled with real project data.

The first one only needs frontend hack and the latter one needs update on the backend.

**Comment by MohammadPCh** [comment]
@aminlatifi @divine-comedian I think it's ok to see them on staging, and for production we can easily not create them there. or remove them if we have.

**Comment by divine-comedian** [comment]
@MohammadPCh - please let us know when we can come back and test this one/

**Comment by MohammadPCh** [comment]
@divine-comedian We've updated the code, and now we only fetch imported project cards.

**Comment by MohammadPCh** [comment]
@divine-comedian do we have to hide not imported projects on my attestation page too? my suggestion is to show it.
