### ISSUE TITLE
Add links to navigate to different pages

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#67]
There should be a few more links added to help users navigate to different pages 

## project card
in addition to the banner image, the project title and description should be a clickable link leading to the project details page

![image](https://github.com/Giveth/DeVouch-FE/assets/67759413/d5d97a69-ded9-44ff-a877-cc9e40f29b2f)

## project details page

on the attester column in the table, clicking the address of the attester should go to the user attestations page for this address

![image](https://github.com/Giveth/DeVouch-FE/assets/67759413/f2d0337b-c530-4f70-a673-a9ae6734f348)

## user attestations page

on the projects column in the table on the user attestations page, clicking the title of the project should go to the project details page for the given project 

![image](https://github.com/Giveth/DeVouch-FE/assets/67759413/4a93f8b9-645c-420d-bcfc-e4ca51041570)

**Comment by maryjaf** [comment]
The tests have been passed.
