### ISSUE TITLE
append URLs for filters & sorts

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#69]
on all views we should handle appending URLs to have filters applied to them, this allows us to share direct links with relevant communities with filters already applied, so they only see the info they care about when the page loads. 

## all projects page 
we should have appended urls for:
- [x] filter by source platform
- [x] filter by attester organization
- [x] sort by highest vouch count
- [x] sort by lowest vouch count
- [x] sort by highest flag count
- [x] sort by lowest flag count

## project details page 
we should have appended urls for:

- [x]  filter by attester organization
- [x] "only vouches" tab
- [x] "only flags" tab
- [x] your attestations tab

## user attestation page (ONLY public)
we should have appended urls for:

- [x] filter by attester organization
- [x] only flags tab
- [x] only vouches tab

**Comment by divine-comedian** [comment]
Assigning @maryjaf as it appears to be in the UAT column..

**Comment by maryjaf** [comment]
> [ ] filter by attester organization

- [ ] this is the link related to filter by attester organization: "Giveth organization team" , is that expected result or  the name of organization should be shown ? @divine-comedian 

https://staging.devouch.xyz/?organization=0xf63f2a7159ee674aa6fce42196a8bb0605eafcf20c19e91a7eafba8d39fa0404

**Comment by divine-comedian** [comment]
@maryjaf - when those tabs are selected by the user on the project details page OR the public user attestations page there is something appended to the URL, it could be for example `tab?=OnlyVouches` 

these are the tabs I'm referring to 
![image](https://github.com/Giveth/DeVouch-FE/assets/67759413/4c4ac054-b4c3-4cae-9262-5818d055d088)

however having URLs on the tabs I would not consider a release blocker.

**Comment by maryjaf** [comment]
> @maryjaf - when those tabs are selected by the user on the project details page OR the public user attestations page there is something appended to the URL, it could be for example `tab?=OnlyVouches`
> 
> these are the tabs I'm referring to ![image](https://private-user-images.githubusercontent.com/67759413/338010524-4c4ac054-b4c3-4cae-9262-5818d055d088.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5OTczMTYsIm5iZiI6MTcxNzk5NzAxNiwicGF0aCI6Ii82Nzc1OTQxMy8zMzgwMTA1MjQtNGM0YWMwNTQtYjRjMy00Y2FlLTkyNjItNTgxOGQwNTVkMDg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDA1MjMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkZDJkYzYxYTZkZThjMjRhMDc3MWE1ODZkZWE3NDkzMGY5MWFlODlhNmE4N2I2OTBhMTQ4OGUyZWE4Y2Q4ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MuyOSnXLKys2d5QtRD_Z9FCCuU2sUBTrECnItgqVE-I)
> 
> however having URLs on the tabs I would not consider a release blocker.

Thanks @divine-comedian 
so It doesn't work as expected.

**Comment by maryjaf** [comment]
> > [ ] filter by attester organization
> 
> * [ ]  this is the link related to filter by attester organization: "Giveth organization team" , is that expected result or  the name of organization should be shown ? @divine-comedian
> 
> https://staging.devouch.xyz/?organization=0xf63f2a7159ee674aa6fce42196a8bb0605eafcf20c19e91a7eafba8d39fa0404

@divine-comedian

**Comment by maryjaf** [comment]
> user attestation page (ONLY public)

Thanks @MohammadPCh it has been fixed but @divine-comedian mentioned that this change should be applied in project page and public user page

When those tabs are selected by the user on  private user attestations page there is also something appended to the URL

**Comment by MohammadPCh** [comment]
@maryjaf Thanks, I think it's acceptable. wdyt @divine-comedian ?
